test ghstack base branch
[ghstack-poisoned]

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -8,14 +8,30 @@ on:
         required: true
 
 jobs:
-  fetch_pr_description:
+
+  pr_base_branch:
     runs-on: ubuntu-latest
     steps:
-      - name: Fetch PR details
-        id: fetch_pr
+      - name: Get PR base branch
+        id: get_pr_base_branch
         run: |
-          PR_DETAILS=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/pytorch/pytorch/pulls/${{ github.event.inputs.pr_number }})
-          PR_DESCRIPTION=$(echo $PR_DETAILS | jq -r '.body')
-          echo "PR_DESCRIPTION=$PR_DESCRIPTION" >> $GITHUB_ENV
-      - name: Print PR description
-        run: echo $PR_DESCRIPTION
+          orig_branch="${{ github.base_ref }}/orig"
+          echo "$orig_branch"
+          orig_branch="${orig_branch/\/head\//}"
+          echo "$orig_branch"
+
+          end=$((SECONDS+100))
+          branch_exists=0
+          while [ $SECONDS -lt $end ]; do
+           git fetch origin
+           if git rev-parse --verify "origin/${orig_branch}"; then
+             branch_exists=1
+             break
+           fi
+           echo "Waiting for branch..."
+           sleep 30  # Wait for 30 seconds before retrying
+          done
+          if [ $branch_exists -eq 0 ]; then
+           echo "Branch not found after 10 minutes."
+           exit 1
+          fi
